version: '3'
services:
  app:
    container_name: resident-graphql-go-app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - residentapp-postgres-db         
    networks:
      - resident


  residentapp-postgres-db:
    image: postgres:9.6.21
    container_name: resident-postgres-db
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '6000:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - resident

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  resident:
    driver: bridge